# Autogenerated wrapper script for miniaudio_jll for i686-linux-musl
export libminiaudio

JLLWrappers.@generate_wrapper_header("miniaudio")
JLLWrappers.@declare_library_product(libminiaudio, "libminiaudio.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libminiaudio,
        "lib/libminiaudio.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
