# Autogenerated wrapper script for miniaudio_jll for i686-w64-mingw32
export libminiaudio

JLLWrappers.@generate_wrapper_header("miniaudio")
JLLWrappers.@declare_library_product(libminiaudio, "libminiaudio.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libminiaudio,
        "bin\\libminiaudio.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
