# Autogenerated wrapper script for miniaudio_jll for x86_64-apple-darwin
export libminiaudio

JLLWrappers.@generate_wrapper_header("miniaudio")
JLLWrappers.@declare_library_product(libminiaudio, "@rpath/libminiaudio.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libminiaudio,
        "lib/libminiaudio.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
